<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="tams_corner" > 
  <xacro:property name="roomheight" value="3.0" />
  <xacro:property name="pi" value="3.1415926535897931" />
  <xacro:property name="tableheight" value="0.75" />

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="brown">
    <color rgba="0.87 0.72 0.53 1"/>
  </material>
  <material name="lightgray">
    <color rgba="0.6 0.6 0.6 1"/>
  </material>
  <link name="floor">
    <inertial>
      <origin xyz="2.5 2.5 0" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="black" />
      <origin xyz="2.5 2.4175 0" />
      <geometry>
        <box size="5.0 5.165 0.001" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="2.5 2.4175 0" />
      <geometry>
      <box size="5.0 5.165 0.001" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="floor">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <!-- kp: stiffness kd: damping mu1, mu2: friction -->
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>
  <link name="wall">
    <inertial>
      <origin xyz="-0.06 2.5 1.5" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="white" />
      <origin xyz="-0.06 2.5 1.5" />
      <geometry>
        <box size="0.12 5.0 3.0" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.06 2.5 1.5" />
      <geometry>
        <box size="0.12 5.0 3.0" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="wall">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <!-- kp: stiffness kd: damping mu1, mu2: friction -->
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <!-- tilted ur5 mount - the meshes are not centered at mount point so they are adjusted to fit to the frame -->
  <link name="ur5_mount">
    <visual>
      <material name="lightgray" />
      <origin xyz="-0.0245 -0.09 -0.28" />
      <geometry>
	<mesh filename="package://tams_ur5_setup_description/meshes/ur5_mount_binary_v3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.0245 -0.09 -0.28" />
      <geometry>
	<mesh filename="package://tams_ur5_setup_description/meshes/ur5_mount_binary_v3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <link name="side_wall">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="white" />
      <origin xyz="0 0 0" />
      <geometry>
        <box size="5.0 0.12 3.0" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.0" />
      <geometry>
        <box size="5.0 0.12 3.0" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="side_wall">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <!-- kp: stiffness kd: damping mu1, mu2: friction -->
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>
  <link name="small_wall">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="white" />
      <origin xyz="0 0 0" />
      <geometry>
              <box size="0.19 0.165 ${roomheight}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.0" />
      <geometry>
        <!-- the collision model is 7cm wider due to security reasons -->
        <box size="0.33 0.305 ${roomheight}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="small_wall">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <!-- kp: stiffness kd: damping mu1, mu2: friction -->
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>
  <link name="cable_duct">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="lightgray" />
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.13 0.06 ${roomheight}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <!-- the collision model is 7cm wider then the actual duct, because of an unmodelled ethernet port -->
        <box size="0.27 0.2 ${roomheight}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="cable_duct">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <!-- kp: stiffness kd: damping mu1, mu2: friction -->
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <link name="table">
    <inertial>
      <origin xyz="0 0 ${tableheight/2}" />
      <mass value="10" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
   <visual>
      <material name="brown" />
      <origin xyz="0 0 ${tableheight/2}" />
      <geometry>
        <box size="0.80 1.0 ${tableheight}" />
      </geometry>
    </visual>
<!-- <collision>
      <origin xyz="0 0 ${tableheight/2}" />
      <geometry>
        <box size="0.80 1.0 ${tableheight}" />
      </geometry>
    </collision>  -->
    <collision>
      <origin xyz="-0.2 0 ${tableheight/2}" />
      <geometry>
        <box size="1.2 1.0 ${tableheight}" />
      </geometry>
    </collision>  

</link>
<gazebo reference="table">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <!-- kp: stiffness kd: damping mu1, mu2: friction -->
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <link name="table_top"/>

  <link name="shelf">
    <inertial>
      <origin xyz="1.7 0 0" />
      <mass value="60" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="lightgray" />
      <origin xyz="0 1.7 0" />
      <geometry>
        <box size="0.4 2 2.5" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 1.7 0" />
      <geometry>
        <!-- the collision model is 7cm wider due to security reasons -->
        <box size="0.54 2.14 2.5" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="shelf">
    <material>Gazebo/Orange</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <!-- kp: stiffness kd: damping mu1, mu2: friction -->
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>


  <link name="april_tag_ur5">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="lightgray" />
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.166 0.166 0.01" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.0" />
      <geometry>
        <box size="0.166 0.166 0.01" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="april_tag_ur5">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <link name="clock">
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2000" />
      <inertia  ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
    </inertial>
    <visual>
      <material name="lightgray" />
      <origin xyz="0 0 0" />
      <geometry>
        <cylinder length="0.06" radius="0.14"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.0" />
      <geometry>
        <cylinder length="0.06" radius="0.14"/>
      </geometry>
    </collision>
  </link>


  <link name="turtlebot" />
  <link name="turtlebot_holder" />


  <joint name="floor_wall_joint" type="fixed">
    <parent link="floor"/>
    <child link="wall"/>
    <!-- The actual wall in the lab is slightly tilted, the rotation compensates approx 1 deg -->
    <origin xyz="0 0 0" rpy="0 0 0" />
    <!--<origin xyz="0 0 0" rpy="0 0.06 0" />-->
  </joint>

  <joint name="wall_mount_joint" type="fixed">
    <parent link="wall"/>
    <child link="ur5_mount"/>
	<origin xyz="0.2255 0.7245 1.085" rpy="0 0 ${pi}" />
  </joint>

  <joint name="side_wall_joint" type="fixed">
    <parent link="floor"/>
    <child link="side_wall"/>
    <!--<origin xyz="2.5 -0.06 1.5" rpy="0 0 0" />-->
    <origin xyz="2.5 -0.225 1.5" rpy="0 0 0" />
  </joint>
  
  <joint name="small_wall_joint" type="fixed">
    <parent link="floor"/>
    <child link="small_wall"/>
    <!--<origin xyz="2.5 -0.06 1.5" rpy="0 0 0" />-->
    <origin xyz="0.07 -0.0825 1.5" rpy="0 0 0" />
  </joint>

  <joint name="cable_duct_joint" type="fixed">
    <parent link="floor"/>
    <child link="cable_duct"/>
    <origin xyz="0.475 -0.135 ${roomheight/2}" rpy="0 0 0" />
  </joint>

  <joint name="table_joint" type="fixed">
    <parent link="floor"/>
    <child link="table"/>
    <!-- actual wall is 2.5cm further back from table, but is modelled at the position of the small ur5 adapter plate -->
   <!-- <origin xyz="0.75 0.3 0" rpy="0 0 0" /> -->
    <origin xyz="0.89 0.74 0" rpy="0 0 0" />
  </joint>

  <joint name="table_top_joint" type="fixed">
    <parent link="table"/>
    <child link="table_top"/>
    <origin xyz="0 0 ${tableheight}" rpy="0 0 0"/>
  </joint>

  <joint name="shelf_joint" type="fixed">
    <parent link="floor"/>
    <child link="shelf"/>
    <!-- actual shelf is a little smaller -->
    <origin xyz="0.2 1 1.25" rpy="0 0 0" />
  </joint>

  <joint name="apriltag_ur5_joint" type="fixed">
    <parent link="wall" />
    <child link="april_tag_ur5" />
    <!--<origin xyz="-0.015 0.75 1.494" rpy="${-pi/2-0.05} 0.0 ${-pi/2}" />--> <!-- offset relative to the tilted wall -->
    <origin xyz="-0.01 0.75 1.494" rpy="${-pi/2} 0.0 ${-pi/2}" /> <!-- offset relative to the tilted wall -->
  </joint>

  <joint name="clock_joint" type="fixed">
    <parent link="wall" />
    <child link="clock" />
    <origin xyz="0.03 0.82 1.993" rpy="${-pi/2} 0.0 ${-pi/2}" /> <!-- offset relative to the tilted wall -->
  </joint>

  <joint name="turtlebot_joint" type="fixed">
    <parent link="world" />
    <child link="turtlebot" />
    <origin xyz="0.26 1.31 0.0" rpy="0.0 0.0 0.0" />
  </joint>

  <joint name="turtlebot_holder_joint" type="fixed">
    <parent link="turtlebot" />
    <child link="turtlebot_holder" />
    <origin xyz="0.04 0.0 0.41" rpy="0.0 0.0 0.0" />
  </joint>

</robot>
